logging:
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS}  [%-5level] [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS}  [%-5level] [%thread] %logger{15} - %msg%n'
#  level: debug



spring:
  profiles:
    active: dev

